export const NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "dwj0v6ggh"; 
export const NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET = "art-express";
export const NEXT_PUBLIC_CLOUDINARY_KEY = "855728716175895";
export const CLOUDINARY_SECRET = "dG_O1Z0rc38IhxFO94zsTPYsXLI";